### ISSUE TITLE
Free Classroom Finder

### ISSUE THREAD

**Issue by Abhinav-ark** [Abhinav-ark/timetable_csea#42]
A page to find all free classrooms at the moment in ab3.

## Todo:
- [ ] Collect timetables of all classrooms in ab3.
- [ ] Store in a custom ADT.
- [ ] Create a new page to list free classrooms floor wise and block wise (A,C,D,F).

**Comment by Ashrockzzz2003** [comment]
Super interesting idea.
Every semester, we should find a way to update this. Just doing it for 1 semester will be useless.

**Comment by SHRIMONESH** [comment]
IAM INTERESTED TO WORK ON THIS ISSUE ? IT WILL GREAT FOR ME IF YOU ASSIGN THIS ISSUE TO ME

**Comment by SHRIMONESH** [comment]
SURE @Abhinav-ark

**Comment by adithya-menon-r** [comment]
Hey @Abhinav-ark, I would like to solve this issue if there is no progress.

**Comment by SHRIMONESH** [comment]
please check my logic approch and suggest the correction to be done @Abhinav-ark

**Comment by Abhinav-ark** [comment]
> Logic Approach - 1:
> 
> Scheduled Classes Page:
> 
> * Input:
>   
>   * Block
>   * Floor
>   * Time Slot
> * Output:
>   
>   * List of all classrooms with their occupied slots.
> 
> Steps:
> 
> 1. Collect Timetables of All Classrooms in AB3
>    The classroom timetables should be collected and stored in a structured format, either CSV or JSON.
> 
> 2.Abstract Data Type The data structure can be represented as follows:
> 
> json: "Block_A": { "Floor_1": { "Room_A101": [(9, 10), (12, 13)], "Room_A102": [(10, 12)] }, "Floor_2": { "Room_A201": [(8, 10.5)] } }
> 
> Free Classrooms Page:
> 
> * Input:
>   
>   * Block
>   * Floor
>   * Time Slot (optional)
> * Output:
>   
>   * List of free classrooms with free intervals.
> 
> Steps:
> 
> 1. Collect Timetables of All Classrooms in AB3
>    The same timetables should be collected and stored in a structured format (CSV or JSON).
> 
> 2.Abstract Data Type The data structure for free classrooms can be represented as follows:
> 
> json: "Block_A": { "Floor_1": { "Room_A101": [(10, 11), (14, 15)], "Room_A102": [(9, 10)] }, "Floor_2": { "Room_A201": [(11, 12.5)] } }
> 
> Interactive Modification Page:
> 
> * Input:
>   
>   * Block
>   * Floor
>   * Room
>   * Slot Modification Action
> * Output:
>   
>   * Updated schedule and free slot list.
> 
> Dynamic Slot Modifications: The interactive modification page allows users to modify slots in real-time by performing the following actions:
> 
> 1.Add Slot
> 
> * If a free slot is available, add it to the scheduled classes and remove from the free slot list.
> 
> 2. Remove Slot
>    
>    * If a slot is occupied, remove it from the scheduled classes and add it back to the free slot list.
> 3. Modify Slot
>    
>    * If a slot needs to be changed, remove the old slot from the scheduled classes and add it back to the free slots.
>    * Then, add the new slot to the scheduled classes.
> 
> Input:
> 
> * Room: Select a room (e.g., A101, B202).
> * Time Slot: Specify the slot to modify (e.g., 9:00 AM – 10:30 AM).
> * Action: Choose whether to Add, Remove, or Modify the slot.
> 
> Interactive Approach:
> 
> * The dynamic slot allocation ensures that changes made on the Free Classrooms page update the Scheduled Classes page and vice versa.
> * This interconnected system ensures efficient data tracking and avoids conflicts in scheduling.

<div align="center">
<img src="https://github.com/user-attachments/assets/0595a287-aa33-42a1-9f25-9ea84d7877db" width="300px">
</div>

@SHRIMONESH I understand you are suggesting a json structure to store the free slots. Come up with an algorithm to do the following:
- [ ] A Main directory which stores csv files of all timetables with classroom name as file name.
- [ ] The CSV should have timetable details of that class.
- [ ] The when run, algorithm should go through all files, and create the json suggested by you.

We won't be dynamically modifying free classrooms for now. That will be for another issue.

**Comment by SHRIMONESH** [comment]
ok , sure i will correct my mistakes.
i will work on it

**Comment by thecodingvivek** [comment]
@Abhinav-ark  I would like to solve this issue if there is no progress Anna.

**Comment by SHRIMONESH** [comment]
Proposed solution:

1. Data organization: Hierarchical Hash Map
2. Algorithm and dynamic Modification: Interval Tree(BST)

Hierarchical Hash Map:

*Organizers classroom by floor and block - Multi-Level nesting
*Provides structured access to specific classroom

Interval Tree:

*Parse the timetable 
*convert the free slots for each classroom into interval tree and populate an interval tree for each classroom

Dynamic Modifications:
 
*Interval trees allow addition , deletion and modification of time slots
*Without interrupt other layers of hash map due to multi-level structure

Node structure:
using low(starting time) and high(ending time) key- [low ,high]

Time:
Hash maps - O(1)
Interval trees - O(log n)

**Comment by SHRIMONESH** [comment]
this is way of approach is correct or not? @Abhinav-ark

**Comment by SHRIMONESH** [comment]
IAM I PROCEED WITH THIS SOLUTION ? @Abhinav-ark
