### ISSUE TITLE
Isolate data from this repository.

### ISSUE THREAD

**Issue by Abhinav-ark** [Abhinav-ark/timetable_csea#44]
## Todo:
- [ ] Remove dependency on direct access of data file, use rest API.
- [ ] Migrate backend to [timetable_oauth Repo](https://github.com/Abhinav-ark/timetable_oauth)  and rename to timetable_backend.
- [ ] Add data files in a new repo for better access management, security and maintainability.

**Comment by Abhinav-ark** [comment]
Assess the feasibility of integrating lowdb for this task <https://github.com/typicode/lowdb>.

**Comment by Praneeth1-O-1** [comment]
I'm interested in contributing to this issue, I can start working on it without a bounty. Please assign me this issue.

**Comment by USER1043** [comment]
I’d like to work on this issue. While I have no prior experience with REST APIs, I have a solid understanding of backend development, repository management, and implementing secure workflows. I’m eager to learn and take on this challenge. Could you please assign this issue to me?

**Comment by Abhinav-ark** [comment]
> HI, I’m interested in working on this issue. While I’m new to REST APIs and secure workflows, I’m eager to learn and apply best practices. I have a basic understanding of backend development and repository management, and I’m confident I can contribute effectively with guidance. Could you please assign this issue to me?

Hi @USER1043, I have assigned you the issue, You have time till Jan 2nd to come up with a partially completed pull request, after which the issue will be reassigned to other participants, if there is no progress.

**Comment by USER1043** [comment]
Thanks for assigning this! I'll begin working and let you know if I have any questions.

**Comment by Ashrockzzz2003** [comment]
@USER1043 any progress?
